$init_user = "
		CREATE USER 'rush'@'localhost' IDENTIFIED BY 'rush123';
		UPDATE mysql.user SET max_questions = 0, max_updates = 0, max_connections = 0 WHERE User = 'rush' AND Host = 'localhost';
		GRANT CREATE USER, ALTER, SUPER, REPLICATION CLIENT, DELETE, CREATE TEMPORARY TABLES, SHOW DATABASES, INSERT, UPDATE, EVENT, ALTER ROUTINE, GRANT OPTION, PROCESS, INDEX, SHUTDOWN, SHOW VIEW, REPLICATION SLAVE, REFERENCES, CREATE ROUTINE, DROP, FILE, SELECT, CREATE, EXECUTE, CREATE VIEW, CREATE TABLESPACE, RELOAD, TRIGGER, LOCK TABLES ON . TO 'rush'@'localhost';
		FLUSH PRIVILEGES;
	";
